/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    FrameView: typeof import('./src/views/FrameView.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    PoemComponent: typeof import('./src/components/PoemComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
